export enum AuthorizationDurationEnum {
  temporary = 'temporary',
  permanent = 'permanent',
}

export enum ScopeEnum {
  account = 'account',
  creddits = 'creddits',
  edit = 'edit',
  flair = 'flair',
  history = 'history',
  identity = 'identity',
  livemanage = 'livemanage',
  modconfig = 'modconfig',
  modcontributors = 'modcontributors',
  modflair = 'modflair',
  modlog = 'modlog',
  modmail = 'modmail',
  modothers = 'modothers',
  modposts = 'modposts',
  modself = 'modself',
  modwiki = 'modwiki',
  modtraffic = 'modtraffic',
  mysubreddits = 'mysubreddits',
  privatemessages = 'privatemessages',
  read = 'read',
  report = 'report',
  save = 'save',
  structuredstyles = 'structuredstyles',
  submit = 'submit',
  subscribe = 'subscribe',
  vote = 'vote',
  wikiedit = 'wikiedit',
  wikiread = 'wikiread',
}
